import Head from "next/head";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
// import LenisWrapper from "./hoc/LenisWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "AS Vision Partners",
  description: "Generated by Anna Schenk",
  other: {
    // Esto es un hack para incluir preload manual
    'link:preload': '/logo/logo-no-bg/logo-white-no-bg.webp',
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="de" suppressHydrationWarning>
      <Head>
        <link
          rel="preload"
          href="/logo/logo-no-bg/logo-white-no-bg.webp"
          as="image"
          type="image/webp"
        />
      </Head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        {/* <Navbar2 /> */}

        {children}

        <Footer />
      </body>
    </html>
  );
}
